### ISSUE TITLE
Require doesn't resolve from the expected path.

### ISSUE THREAD

**Issue by 0xR** [TheBrainFamily/cypress-cucumber-preprocessor#30]
In a file inside `cypress/support/step_definitions` I require a file `./bla`. When I view the network tab of the devtools I see this error: 

```
(function () {
  Cypress.action("spec:script:error", {
    type: "BUNDLE_ERROR",
    error: "Error: Cannot find module './bla' from '<project-path>/cypress/integration'{newline}"
  })
}())
```

I expect it to resolve from `cypress/support/step_definitions` and not `cypress/integration`

**Comment by 0xR** [comment]
Importing relative to `/integration` does work. However restarting cypress gives this error:

```
 Error running plugin
The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.

Error: Cannot find module '../support/step_definitions/bla' from '/home/rjs/workspaces/suitsupply/cypress-demo/cypress/support/step_definitions'
```

**Comment by lgandecki** [comment]
Oh, interesting. We will fix this soon, thanks for letting us know!

**Comment by lgandecki** [comment]
This is fixed in 0.4.0 , please give it a try, and if still doesn't work as needed please create a new issue.

**Comment by vlavellauruit** [comment]
I'm currently under this issue too. I'm working with the v 1.0.0. I can't figure it out why this is happening

**Comment by rickschubert** [comment]
I am having the same problem as @vlavellauruit, both on 0.6.0 and 1.0.0

**Comment by lgandecki** [comment]
@vlavellauruit @rickschubert is this still a problem in the current version? It'd be great for a simple reproduction, it's very hard to debug problem like this. Hard to say if the problems you guys are exactly like the guy above - it shouldn't be, as that particular source of the problem was fixed.

**Comment by rickschubert** [comment]
@lgandecki The imports only work if the feature file and the step defintion file are both on the same "level", i.e. with the following structure:

```
- features/
-- stuff.feature
- step_definitions/
-- stuff.js
```

As soon as it gets more complicated, it doesn't work anymore, i.e.
```
- features/
-- stuff.feature
- step_definitions/
-- stuff.js
-- folder_with_files_to_import/
--- file_getting_imported_by_stuff.js
```

**Comment by lgandecki** [comment]
What version are you using when it doesn't work?

**Comment by rickschubert** [comment]
@lgandecki We were using version 1.0.0.

**Comment by lgandecki** [comment]
This is possibly fixed in 1.2.0 https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/CHANGELOG.md#120---2018-07-13
